import type { DeviceKind, EnemyKind, RgbPower } from './types'
import { visibleColor } from './rules'

// Original 16 × 16 sprites. The same atlas draws the field and the instrument menu.
// k = black, d = graphite, m = silver, w = white, c = the live optical spectrum.
export const PIXEL_INK = {
  k: '#080808', d: '#444444', m: '#999999', w: '#f5f5f5',
  r: '#ff243b', g: '#24ff72', b: '#2864ff',
} as const

export const SPECTRUM = {
  red: 0xff243b, green: 0x24ff72, blue: 0x2864ff, yellow: 0xffee24,
  orange: 0xff7b24, magenta: 0xff24e5, cyan: 0x24edff, white: 0xffffff, dark: 0x777777,
} as const

export function spectrumColor(power: RgbPower): number {
  return SPECTRUM[visibleColor(power)]
}

export function sourceAccent(kind: DeviceKind): string {
  return kind === 'source-red' ? PIXEL_INK.r : kind === 'source-green' ? PIXEL_INK.g : kind === 'source-blue' ? PIXEL_INK.b : PIXEL_INK.w
}

const sprite = (rows: string): readonly string[] => rows.trim().split('\n').map((row) => row.trim())

const source = sprite(`
................
......mmmm......
....mmddddmm....
...mddkkkkddm...
..mdkkwwwwkkdm..
.mdkkwddddwkkdm.
.mdkwddccddwkdm.
.mdkwdccccdwkdm.
.mdkwdccccdwkdm.
.mdkwddccddwkdm.
.mdkkwddddwkkdm.
..mdkkwwwwkkdm..
...mddkkkkddm...
....mmddddmm....
......mmmm......
................`)

export const DEVICE_SPRITES: Record<DeviceKind, readonly string[]> = {
  'source-red': source, 'source-green': source, 'source-blue': source,
  mirror: sprite(`
................
...........ww...
..........wwm...
.........wwmd...
........wwmd....
.......wwmd.....
......wwmd......
.....wwmd.......
....wwmd........
...wwmd.........
..wwmd..........
..wmd...........
...d...mm.......
.....mmddmm.....
.....mmmmmm.....
................`),
  splitter: sprite(`
................
.......mm.......
......mwwm......
.....mwddwm.....
....mwddddwm....
...mwddwwddwm...
..mwddwkkwddwm..
.mwddwccccwddwm.
.mwddwccccwddwm.
..mwddwkkwddwm..
...mwddwwddwm...
....mwddddwm....
.....mwddwm.....
......mwwm......
.......mm.......
................`),
  'prism-splitter': sprite(`
................
.......ww.......
.......ww.......
......wmmw......
......wmmw......
.....wmddmw.....
.....wmddmw.....
....wmddddmw....
....wmddddmw....
...wmddddddmw...
...wmddddddmw...
..wmddrrggbbmw..
..wmddrrggbbmw..
.wwwwwwwwwwwwww.
................
................`),
  combiner: sprite(`
................
..mm........mm..
..wwmm....mmww..
....wwmmddww....
......wwww......
.....mdkkdm.....
....mdkcckdm....
....mdccccdm....
....mdccccdm....
....mdkcckdm....
.....mdkkdm.....
......wwww......
.......cc.......
.......cc.......
.......ww.......
................`),
  filter: sprite(`
................
....mmmmmmmm....
...mwwwwwwwwm...
...mwkkkkkkwm...
...mwkcccckwm...
...mwkcccckwm...
...mwkcccckwm...
.ddmwkcccckwmdd.
.ddmwkcccckwmdd.
...mwkcccckwm...
...mwkcccckwm...
...mwkkkkkkwm...
...mwwwwwwwwm...
....mmmmmmmm....
................
................`),
  collector: sprite(`
................
.ww..........ww.
.wmw........wmw.
..wmw......wmw..
...wmw....wmw...
....wmw..wmw....
.....wmwwmw.....
......wccw......
......wccw......
.....mwccwm.....
....mwwwwwwm....
....mdkkkkdm....
....mdmmmmdm....
....mwwwwwwm....
.....mmmmmm.....
................`),
  bulb: sprite(`
................
......wwww......
....wwmmmmww....
...wmddddddmw...
..wmddccccddmw..
..wmddccccddmw..
..wmddccccddmw..
...wmddccddmw...
....wmddddmw....
.....wwwwww.....
.....mdkkdm.....
.....mwwwwm.....
.....mdkkdm.....
....mmmmmmmm....
....wwwwwwww....
................`),
  'laser-emitter': sprite(`
................
......wwww......
......wccw......
......wccw......
......wccw......
......wccw......
.....mmccmm.....
....mwkcckwm....
...mwkkcckkwm...
...mwkkkkkkwm...
...mwwwwwwwwm...
...mdkkkkkkdm...
...mdmmmmmmdd...
..mmwwwwwwwwmm..
..wwddddddddww..
................`),
  'radiation-source': sprite(`
................
......mmmm......
....mmwwwwmm....
...mwddkkddwm...
..mwdddkkdddwm..
..mwkkdccdkkwm..
.mwkkdccccdkkwm.
.mwddccccccddwm.
.mwddccccccddwm.
.mwkkdccccdkkwm.
..mwkkdccdkkwm..
..mwdddkkdddwm..
...mwddkkddwm...
....mmwwwwmm....
......mmmm......
................`),
  'frost-tower': sprite(`
................
.......ww.......
......wccw......
.....wccccw.....
....wccccccw....
...wccccccccw...
..wwccccccccww..
..mwccccccccwm..
...mwccccccwm...
....mwccccwm....
.....mwwwwm.....
....mdkkkkdm....
...mdmmmmmmdd...
...mwwwwwwwwm...
....mmmmmmmm....
................`),
  brazier: sprite(`
................
........c.......
.....c.cc.......
.....cccc.c.....
....ccccccc.....
....ccwwccc.....
.....cwwcc......
..wwwwwwwwwwww..
..mddddddddddm..
...mddddddddm...
....mwwwwwwm....
.....mdkkdm.....
.....mdkkdm.....
....mwwwwwwm....
....mmmmmmmm....
................`),
  accelerator: sprite(`
................
...ww......ww...
...wm......mw...
...wmd.cc.dmw...
...wmd.cc.dmw...
...wmd.cc.dmw...
...wmd.cc.dmw...
...wmd.cc.dmw...
...wmd.cc.dmw...
...wmd.cc.dmw...
...wmd.cc.dmw...
...wmd.cc.dmw...
...wmmmmmmmmw...
...wwwwwwwwww...
....dddddddd....
................`),
  shutter: sprite(`
................
..wwwwwwwwwwww..
..wmkkkkkkkkmw..
..wmwwwwddddmw..
..wmwwwwddddmw..
..wmwwwwddddmw..
..wmwwwwddddmw..
..wmwwccccddmw..
..wmwwccccddmw..
..wmwwwwddddmw..
..wmwwwwddddmw..
..wmwwwwddddmw..
..wmkkkkkkkkmw..
..wwwwwwwwwwww..
................
................`),
  'photo-sensor': sprite(`
................
....wwwwwwww....
...wmkkkkkkmw...
..wmkwwwwwwkmw..
..wmkwccccwkmw..
..wmkwccccwkmw..
..wmkwccccwkmw..
..wmkwwwwwwkmw..
...wmkkkkkkmw...
....wwwwwwww....
.......mm.......
.......mm.......
.......mm.......
.....wwwwww.....
.....mmmmmm.....
................`),
  capacitor: sprite(`
................
.....ww..ww.....
.....mm..mm.....
...wwwwwwwwww...
..wmddddddddmw..
..wmdccccccdmw..
..wmdccccccdmw..
..wmddddddddmw..
..wmdccccccdmw..
..wmdccccccdmw..
..wmddddddddmw..
..wmdccccccdmw..
..wmdccccccdmw..
..wmddddddddmw..
...wwwwwwwwww...
................`),
}

export const ENEMY_SPRITES: Record<EnemyKind, readonly string[]> = {
  normal: sprite(`
................
................
.....wwwwww.....
....wmmmmmmw....
...wmmddddmmw...
...wmwwddwwmw...
...wmwkddkwmw...
...wmddddddmw...
....wmmmmmmw....
.....wwwwww.....
...mmddmmddmm...
...wwddwwddww...
....ww....ww....
................
................
................`),
  fast: sprite(`
................
................
........ww......
......wwmmw.....
.....wmmddmw....
...wwmmwwwdmw...
..wmmmwwkkddmw..
.wmmmwddddddmw..
..wmmmwwkkddmw..
...wwmmwwwdmw...
.....wmmddmw....
......wwmmw.....
........ww......
................
................
................`),
  armored: sprite(`
................
....wwwwwwww....
...wmmmmmmmmw...
..wmddddddddmw..
..wmwwwwwwwwmw..
.wwmwwkkkkwwmww.
.wdmwwkkkkwwmdw.
.wdmddddddddmdw.
.wdmddddddddmdw.
.wwmwwwwwwwwmww.
..wmddddddddmw..
...wmmmmmmmmw...
....wwwwwwww....
...wwww..wwww...
...dddd..dddd...
................`),
  resistant: sprite(`
................
.......ww.......
......wmmw......
.....wmmmmw.....
....wmmddmmw....
...wmddccddmw...
..wmddccccddmw..
.wmddccwwccddmw.
.wmddccwwccddmw.
..wmddccccddmw..
...wmddccddmw...
....wmmddmmw....
.....wmmmmw.....
......wmmw......
.......ww.......
................`),
  boss: sprite(`
..ww........ww..
..wmw......wmw..
..wmmwwwwwwmmw..
...wmmmmmmmmw...
..wmddddddddmw..
.wmwwwwddwwwwmw.
.wmwkkwddwkkwmw.
.wmwkkwddwkkwmw.
.wmddddddddddmw.
.wwmwwwwwwwwmww.
.wdmwkkkkkkwmdw.
.wdmwmmmmmmwmdw.
.wwmwmmmmmmwmww.
..wwwwwwwwwwww..
..wwww....wwww..
..dddd....dddd..`),
}

export const CORE_SPRITE = sprite(`
.....wwwwww.....
...wwmmmmmmww...
..wmmddddddmmw..
.wmddwwwwwwddmw.
.wmddwddddwddmw.
wmddwddwwddwddmw
wmdwddwccwddwdmw
wmdwdwccccwdwdmw
wmdwdwccccwdwdmw
wmdwddwccwddwdmw
wmddwddwwddwddmw
.wmddwddddwddmw.
.wmddwwwwwwddmw.
..wmmddddddmmw..
...wwmmmmmmww...
.....wwwwww.....`)

export type PixelRun = { x: number; y: number; width: number; ink: string }

const runCache = new Map<readonly string[], readonly PixelRun[]>()

export function pixelRuns(rows: readonly string[]): readonly PixelRun[] {
  const cached = runCache.get(rows)
  if (cached) return cached
  const runs: PixelRun[] = []
  rows.forEach((row, y) => {
    for (let x = 0; x < row.length;) {
      const ink = row[x]
      const start = x++
      while (row[x] === ink) x++
      if (ink !== '.') runs.push({ x: start, y, width: x - start, ink })
    }
  })
  runCache.set(rows, runs)
  return runs
}
